# Generated by Django 4.0.2 on 2022-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_task_detail_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
