# Generated by Django 4.0.2 on 2022-10-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_task_content_alter_task_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
