# Generated by Django 4.0.2 on 2022-10-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', 'deadline']},
        ),
    ]
